services:
  db:
    image: postgres:15
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sr
      POSTGRES_PASSWORD: vHC4jr7LVq1I4D2x0rLG
      POSTGRES_DB: sr
    ports:
      - "5432:5432"
    volumes:
      - sr_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sr"]
      interval: 5s
      timeout: 5s
      retries: 5

  trader:
    build:
      context: ./src
      dockerfile: trader/Dockerfile
    container_name: trader
    restart: unless-stopped
    volumes:
      - ./src:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://sr:vHC4jr7LVq1I4D2x0rLG@db:5432/sr
    command: python trader/main.py
    depends_on:
      db:
        condition: service_healthy

  api:
    build:
      context: ./src
      dockerfile: api/Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://sr:vHC4jr7LVq1I4D2x0rLG@db:5432/sr
    command: python api/main.py
    depends_on:
      db:
        condition: service_healthy

  web:
    build: ./web
    container_name: web
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules

volumes:
  sr_data:
